# Generated by Django 5.1.2 on 2025-02-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
